name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  JAX_VERSION : 0.4.23
  JAX_CONDA_IMAGE_NAME : "yfukai/conda-jax"
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.2.1'

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata (JAX conda CPU)
        id: meta_jax_conda
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.JAX_CONDA_IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Extract Docker metadata (JAX conda GPU)
        id: meta_jax_conda_cuda
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.JAX_CONDA_IMAGE_NAME }}
          tags: |
            type=schedule,suffix=-cuda
            type=ref,event=branch,suffix=-cuda
            type=ref,event=tag,suffix=-cuda
            type=ref,event=pr,suffix=-cuda

      - name: Extract Docker metadata (CPU)
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Extract Docker metadata (GPU)
        id: meta_cuda
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,suffix=-cuda
            type=ref,event=branch,suffix=-cuda
            type=ref,event=tag,suffix=-cuda
            type=ref,event=pr,suffix=-cuda

      - name: Delete image (JAX conda CPU)
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: yfukai
          name: ${{ env.JAX_CONDA_IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.meta_jax_conda.outputs.tags }}

      - name: Delete image (JAX conda GPU)
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: yfukai
          name: ${{ env.JAX_CONDA_IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.meta_jax_conda_cuda.outputs.tags }}

      - name: Delete image (JAX conda CPU)
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: yfukai
          name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.meta.outputs.tags }}

      - name: Delete image (JAX conda GPU)
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: yfukai
          name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.meta_cuda.outputs.tags }}
